Remove all obsolete items and item members (#54)
NetTopologySuite/GeoAPI pull request #56
Opened 2018-10-09 08:07 UTC by FObermaier

The following items are removed:
* GeoAPI.Geometries.ICoordinate
* GeoAPI.Geometries.IEnvelope
* GeoAPI.Operation.Buffer.BufferStyle

The following interface implementations have been removed
* System.ICloneable

The folling members were removed:
* Envelope.Overlaps
* IMultiLineString.Reversed
* ICoordinateSequence.Reversed
* IGeometry.Equals
* IGeometryFactory.CreateMultiLineString(CoordinateXY[])

Unit test have been adapted; minor changes to Interval
Changed IMathTransform to use CoordinateXY

Closes #54 
Closes #31

2018-11-04 18:26 UTC, airbreather requested changes
Sorry it took me so long to get to this; I did a brief look when it was submitted and saw some things I really didn't like, so I decided I needed to dedicate some serious time to thinking about it... and then I completely forgot about it until your comment on Gitter 😶...

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/Coordinate.cs
> +                return ((CoordinateXY) this).Equals(otherXY);
this cast allocates a new instance, which bothers me in a method like this.

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +        public sealed override bool Equals(object o)
Sealing `Equals` and `GetHashCode`, in a class that's otherwise designed with inheritance in mind, really bothers me...

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI.CoordinateSystems/CoordinateSystems/Transformations/IMathTransform.cs
> +        CoordinateXY Transform(CoordinateXY coordinate);
This doesn't feel right when the input and output dimensions differ.

Perhaps the interface should be declared as:
```csharp
public interface IMathTransform<TInput, TOutput>
    where TInput: CoordinateXY
    where TOutput: CoordinateXY
{
    /* ... */
}
```

using it would then look like:
```csharp
IMathTransform<CoordinateXY, CoordinateXYZ> transform2dTo3d = /* ... */;
CoordinateXY coord2d = /* ... */;
CoordinateXYZ coord3d = transform2dTo3d.Transform(coord2d);
```

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +            return false;
`Coordinate`'s override of `Equals(object)` has special-casing for `CoordinateXY`; because of that, it seems like this should also special-case `Coordinate` so that these two don't differ:

```csharp
object a = new Coordinate();
object b = new CoordinateXY();
WriteLine(a.Equals(b)); // true
WriteLine(b.Equals(a)); // false
```

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/Coordinate.cs
> +            if (o is CoordinateXY otherXY)
not sure this makes sense... .NET equality semantics are complicated enough to get right under "normal" circumstances, so allowing instances of this type to be treated as equal to instances of unrelated types feels awkward at best.

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +        /// Returns a <c>string</c> of the form <I>(x,y,z)</I> .
wrong format

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +    public class CoordinateXY : IComparable<CoordinateXY>
above this, the xmldoc refers to `Coordinate` instead of `CoordinateXY`

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +    public class CoordinateXY : IComparable<CoordinateXY>
a few other references in this file too

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/Coordinate.cs
> +    public class Coordinate : IComparable<Coordinate>
this also used to implement the `IComparable` interface through `ICoordinate`; that should probably be brought in here too.

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> -    public class CoordinateXY : IComparable<CoordinateXY>, ICoordinate
this also used to implement the `IComparable` and `ICloneable` interfaces through `ICoordinate`; those should probably be brought in here too.

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/Coordinate.cs
> -    public class Coordinate : ICoordinate, IComparable<Coordinate>
Part of this idea was to do a "clean break" from the old version of stuff.  To that end, is there a reason to keep `Coordinate` around at all when everything else should be using `CoordinateXY`?

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +    public class CoordinateXY : IComparable<CoordinateXY>
Running through a bunch of weird scenarios in my mind, the way that we have things set up, I keep arriving at the conclusion that we shouldn't support external consumers inheriting from these types.

What do you think about having it set up so that this can't happen, maybe by having all `CoordinateXY` constructors throw if `this.GetType()` isn't one of our four?

2018-11-04 18:26 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> -    public class CoordinateXY : IComparable<CoordinateXY>, ICoordinate
`CompareTo(object)` (which I can't comment on directly in this PR because it's outside the diff) is incorrect; we're supposed to throw `ArgumentException` if the instances are of incompatible types.  Otherwise, there's no way to guarantee that `a.CompareTo(b)` and `b.CompareTo(a)` are always consistent with one another (which is a requirement for many sorting algorithms... see also NetTopologySuite/NetTopologySuite#260)

2018-11-04 18:28 UTC, airbreather commented
One more thing, `IGeometryServices.cs` has a delegate that's marked `[Obsolete("Not used", true)]` which seems like it could go away now too.

2018-11-22 11:50 UTC, FObermaier commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +        public sealed override bool Equals(object o)
For the functions/objects working with `Coordiante` it is vital that this semantic is not changed.
The inheritance ends at either Coordinate[XY]M or Coordinate[XY]ZM.

Reading http://blogs.microsoft.co.il/sasha/2007/02/27/jit-optimizations-inlining-and-interface-method-dispatching-part-1-of-n/, I got the impression with sealing these functions we might get some performance benfit. I will prove that.

2018-11-22 11:52 UTC, FObermaier commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +            return false;
According to #55 I think we should remove `Coordinate` altogether.

2018-11-22 11:54 UTC, FObermaier commented on src/GeoAPI/Geometries/Coordinate.cs
> -    public class Coordinate : ICoordinate, IComparable<Coordinate>
I think not. (see #55)

2018-11-22 11:56 UTC, FObermaier commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +    public class CoordinateXY : IComparable<CoordinateXY>
That is a reason for `sealed` `Equals` and `GetHashCode`

2018-11-22 11:57 UTC, FObermaier commented on src/GeoAPI/Geometries/CoordinateXY.cs
> -    public class CoordinateXY : IComparable<CoordinateXY>, ICoordinate
We can create a new issue for that.

2018-11-27 13:34 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +        public sealed override bool Equals(object o)
>  The inheritance ends at either Coordinate[XY]M or Coordinate[XY]ZM.

Right, I suggested elsewhere that it might be appropriate to find a way to **enforce** that, since nothing stops external consumers making their own class that inherits from `CoordinateXY` or `CoordinateXYZ` (because we leave them unsealed so that **we** can inherit from them).

> with sealing these functions we might get some performance benfit.

Theoretically, the performance benefits of sealing `Equals(object)` and `GetHashCode()` overrides would only happen when they're called directly from code that **knows** that it's `CoordinateXY`.

If the instances are put into `HashSet<CoordinateXY>` or `Dictionary<CoordinateXY, Something>` (or similar), then it's still an indirect call.

2019-02-12 09:34 UTC, FObermaier commented on src/GeoAPI/Geometries/Coordinate.cs
> +                return ((CoordinateXY) this).Equals(otherXY);
Now it is me who has to apologize, I've been really busy.
Given that #55 suggest we remove `Coordinate` altogether and replace it with a renamed `CoordinateXY` we don't need to bother about this, do we?

2019-02-12 09:36 UTC, FObermaier commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +        public sealed override bool Equals(object o)
We leave `Equals` and `GetHashcode` sealed?

2019-02-12 09:37 UTC, FObermaier commented on src/GeoAPI/Geometries/Coordinate.cs
> +            if (o is CoordinateXY otherXY)
dito

2019-02-12 09:37 UTC, FObermaier commented on src/GeoAPI/Geometries/Coordinate.cs
> +    public class Coordinate : IComparable<Coordinate>
dito

2019-02-12 09:40 UTC, FObermaier commented on src/GeoAPI/Geometries/CoordinateXY.cs
> -    public class CoordinateXY : IComparable<CoordinateXY>, ICoordinate
`ICloneable` was "necessary" because JTS used to use `Clone`. It was superceeded with `Copy` so we shouldn't bring `ICloneable` in again.
Good catch for `IComparable`

2019-02-12 11:44 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> +        public sealed override bool Equals(object o)
> We leave `Equals` and `GetHashcode` sealed?

Yes, I think that's fine.

The idea I'd had about trying to **enforce** that nobody else can inherit from `CoordinateXY` seems unreasonable because the only implementations I can think of would likely have unacceptable performance impacts.

2019-02-12 11:45 UTC, airbreather commented on src/GeoAPI/Geometries/Coordinate.cs
> +                return ((CoordinateXY) this).Equals(otherXY);
> we don't need to bother about this, do we?

Agreed, let's remove `Coordinate` soon... outside of this PR :grin:

2019-02-12 11:51 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> -    public class CoordinateXY : IComparable<CoordinateXY>, ICoordinate
> `ICloneable` was "necessary" because JTS used to use `Clone`. It was superceeded with `Copy` so we shouldn't bring `ICloneable` in again.

OK.  I'm not 100% sure on this one because of other `ICloneable` implementations throughout the library and consistency with earlier versions of GeoAPI, but I do kinda hate this interface (see [Notes to Implementers](https://docs.microsoft.com/en-us/dotnet/api/system.icloneable#notes-to-implementers) in the documentation), so I'm OK with omitting it.

Just `IComparable` then

2019-02-12 11:54 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> -    public class CoordinateXY : IComparable<CoordinateXY>, ICoordinate
> We can create a new issue for that.

#58

2019-02-13 08:02 UTC, FObermaier commented on src/GeoAPI/Geometries/CoordinateXY.cs
> -    public class CoordinateXY : IComparable<CoordinateXY>, ICoordinate
From the notes to implementers:

> ..., we recommend that ICloneable not be implemented in public APIs.

As we are breaking previous code anyway, we should consider removing `ICloneable` from our interfaces and classes altogether.

2019-02-13 14:01 UTC, FObermaier commented on src/GeoAPI.CoordinateSystems/CoordinateSystems/Transformations/IMathTransform.cs
> +        CoordinateXY Transform(CoordinateXY coordinate);
This is technically not possible. Given a `IMathTransform` that requires `CoordinateXY` and returns `CoordinateXYZ` you can't call `Invert()` on it to make it compute in the opposite direction:
https://github.com/NetTopologySuite/GeoAPI/blob/fc8494e90579cda33586b4b680912a84ae4c57c7/src/GeoAPI.CoordinateSystems/CoordinateSystems/Transformations/IMathTransform.cs#L184-L187

2019-02-13 14:18 UTC, airbreather commented on src/GeoAPI.CoordinateSystems/CoordinateSystems/Transformations/IMathTransform.cs
> +        CoordinateXY Transform(CoordinateXY coordinate);
Oh jeez, OK, that's a good point.

2019-02-13 14:25 UTC, airbreather commented on src/GeoAPI/Geometries/CoordinateXY.cs
> -    public class CoordinateXY : IComparable<CoordinateXY>, ICoordinate
#59 opened

2019-02-14 11:57 UTC, FObermaier commented
I did add `ICloneable` to `CoordinateXY` so we can decide to remove it when we tackle #59.

2019-02-14 13:40 UTC, airbreather approved these changes

2019-02-14 14:00 UTC, merged